# Generated by Django 5.2.6 on 2025-09-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0002_alter_zona_latitud_alter_zona_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='zona',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
