# Generated by Django 5.2.6 on 2025-09-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0003_alter_zona_latitud_alter_zona_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='longitud',
        ),
        migrations.AddField(
            model_name='zona',
            name='area',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
