# Generated by Django 5.2.6 on 2025-09-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_envio_latitud_destino_envio_latitud_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='latitud_destino',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='latitud_origen',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='longitud_destino',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='longitud_origen',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
