# Generated by Django 5.2.6 on 2025-09-25 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_alter_envio_latitud_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='monto_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='tipo',
            field=models.CharField(choices=[('Recojo', 'Recojo'), ('Envío', 'Envío')], default='Envío', max_length=15),
        ),
        migrations.AddField(
            model_name='envio',
            name='tipo_pago',
            field=models.CharField(choices=[('En Origen', 'En Origen'), ('En Destino', 'En Destino')], default='En Origen', max_length=15),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='envios.envio'),
        ),
        migrations.AlterField(
            model_name='historialenvio',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='envios.envio'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='envios.envio'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_id', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=15)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='envios.envio')),
            ],
        ),
    ]
