# Generated by Django 5.2.6 on 2025-09-25 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_envio_monto_pago_envio_tipo_envio_tipo_pago_and_more'),
        ('usuarios', '0003_perfilmensajero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='foto',
        ),
        migrations.AddField(
            model_name='entrega',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='envio',
            name='mensajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajero', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='envio',
            name='remitente_nombre',
            field=models.CharField(default='PruebaValor', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envio',
            name='remitente_telefono',
            field=models.CharField(default='PruebaValor', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrega',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.envio'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitente', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='tipo_pago',
            field=models.CharField(choices=[('Origen', 'Origen'), ('Destino', 'Destino')], max_length=15),
        ),
        migrations.AlterField(
            model_name='historialenvio',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.envio'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.envio'),
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
