# Generated by Django 5.2.6 on 2025-10-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0005_remove_entrega_foto_entrega_pagado_envio_mensajero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='estado',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Resuelto', 'Resuelto')], default='Pendiente', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Retraso', 'Retraso'), ('Daño', 'Daño'), ('Pérdida', 'Pérdida'), ('Otro', 'Otro')], max_length=20, null=True),
        ),
    ]
