# Generated by Django 5.2.6 on 2025-10-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0006_alter_incidente_descripcion_alter_incidente_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
