# Generated by Django 5.2.6 on 2025-10-08 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0007_envio_qr_code'),
        ('usuarios', '0003_perfilmensajero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='remitente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remitente', to='usuarios.usuario'),
        ),
    ]
