# Generated by Django 5.2.6 on 2025-09-23 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilMensajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_mensajero', to='usuarios.usuario')),
            ],
        ),
    ]
