# Generated by Django 5.2.6 on 2025-09-09 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('duracion_estimada', models.IntegerField(blank=True, null=True)),
                ('duracion_real', models.IntegerField(blank=True, null=True)),
                ('latitud_inicio', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud_inicio', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitud_fin', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud_fin', models.DecimalField(decimal_places=6, max_digits=9)),
                ('mensajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas.zona')),
            ],
            options={
                'unique_together': {('mensajero', 'fecha')},
            },
        ),
    ]
