# Generated by Django 5.2.6 on 2025-09-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='retraso_estimado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='zona_asignada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
