# Generated by Django 5.2.6 on 2025-09-30 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0005_remove_entrega_foto_entrega_pagado_envio_mensajero_and_more'),
        ('rutas', '0002_ruta_retraso_estimado_ruta_zona_asignada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envios.envio'),
        ),
    ]
