# Generated by Django 5.2.6 on 2025-10-01 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0005_remove_entrega_foto_entrega_pagado_envio_mensajero_and_more'),
        ('rutas', '0003_ruta_envio'),
        ('usuarios', '0003_perfilmensajero'),
        ('zonas', '0004_remove_zona_latitud_remove_zona_longitud_zona_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterUniqueTogether(
            name='ruta',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='duracion_estimada',
            field=models.IntegerField(blank=True, help_text='Duración estimada en minutos', null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='duracion_real',
            field=models.IntegerField(blank=True, help_text='Duración real en minutos', null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='envios.envio'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='latitud_fin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='latitud_inicio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='longitud_fin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='longitud_inicio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='mensajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='retraso_estimado',
            field=models.CharField(blank=True, choices=[('Retraso estimado', 'Retraso estimado'), ('Entrega a tiempo', 'Entrega a tiempo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='zonas.zona'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='zona_asignada',
            field=models.IntegerField(blank=True, help_text='Cluster asignado por K-Means', null=True),
        ),
    ]
