# Generated by Django 5.2.6 on 2025-10-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0004_alter_ruta_options_alter_ruta_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='distancia_google_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='polyline_google',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='duracion_estimada',
            field=models.IntegerField(blank=True, help_text='Duración estimada en minutos (Google)', null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='duracion_real',
            field=models.IntegerField(blank=True, help_text='Duración real en minutos (app móvil)', null=True),
        ),
    ]
